### ISSUE TITLE
Nftables in miniupnpd (latest revision from git)

### ISSUE THREAD

**Issue by rtorrentuser** [miniupnp/miniupnp#380]
When I start uTorrent (which uses UPNP) rules are added to nftables as follows:

table ip filter {
	chain MINIUPNPD {
		iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
		iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
	}
}
table ip nat {
	chain MINIUPNPD {
		iif "br1" udp dport 16422 dnat to 192.168.0.4:16422
		iif "br1" tcp dport 16422 dnat to 192.168.0.4:16422
	}
}

Upon program exit only rules in 'table ip nat' are deleted and those in 'table ip filter' remain "forever":

table ip filter {
	chain MINIUPNPD {
		iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
		iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
	}
}
table ip nat {
	chain MINIUPNPD {
	}
}

I think that this is a wrong behavior...

**Comment by miniupnp** [comment]
@svenauhagen any idea ?

**Comment by svenauhagen** [comment]
@miniupnp general question, does miniupnpd flush the chains on exit or do I have to use the scripts?

**Comment by miniupnp** [comment]
miniupnpd does not flush anything on exit !

the problem here is that the nat rules have been removed, but not the filter one.
I think it is utorrent who asked to remove the port mapping when exiting

**Comment by rtorrentuser** [comment]
Sorry, my description of  the problem was incomplete...  The main point is not that the filter rules are not removed on program exit. The problem is that absolutely the same filter rules are added on each program start to already existing in the table. So eventually we see numerous identical records:

table ip filter {
chain MINIUPNPD {
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol udp accept
iif "br1" @th,16,16 16422 ip daddr 192.168.0.4 ip protocol tcp accept
......
}
}

So I think that either the rules should be removed on every program exit or there should be some check to prevent adding already existing rules on every program start...

**Comment by miniupnp** [comment]
@rtorrentuser you mean at every miniupnpd exit ? or uTorrent exit ?

**Comment by rtorrentuser** [comment]
On uTorrent exit. I don't know whether the rules should be removed on uTorrent exit but duplicate rules definitely should not be created on next uTorrent start...

**Comment by miniupnp** [comment]
on uTorrent exit, uTorrent sends a "DeletePortMapping" request. It should remove both the filter and the nat rules.

**Comment by miniupnp** [comment]
call "stack" :
DeletePortMapping()
upnp_delete_redirection()
_upnp_delete_redir()
delete_redirect_and_filter_rules()

something must be wrong in https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter_nft/nftnlrdr.c#L238

**Comment by rtorrentuser** [comment]
>on uTorrent exit, uTorrent sends a "DeletePortMapping" request. It should remove both the filter and the nat rules.

But it doesn't! Only nat rule is removed... And duplicate filter rule is created every start of uTorrent.  Tried with two more programs with the same result.

**Comment by miniupnp** [comment]
yes that's the bug. The delete_redirect_and_filter_rules() function in netfilter_nft/nftnlrdr.c should remove both rules, but fails to remove the filter rule.

I cannot work on nft version right now. could @svenauhagen investigate further ?

**Comment by svenauhagen** [comment]
@rtorrentuser are you using the scripts from the netfilter_nft folder to create the tables?
I changed the filter table to inet so it can hold IPv4 and IPv6 but I just saw that the script is incorrect now.
This might be the cause of the issue.

**Comment by svenauhagen** [comment]
@rtorrentuser ok so the chain seems to have gotten mixed up in the merge to IPV4 only.
I fixed that and also the scripts in this branch:
https://github.com/svenauhagen/miniupnp/tree/fixes/nftables

can you test it on your end?

**Comment by rtorrentuser** [comment]
> can you test it on your end?

Unfortunately the problem persists... The filter rules are not removed on uTorrent exit and what is more annoying same rules are added on next uTorrent start despite the fact that they are already in the filter table... So after 3 starts-exits of uTorrent the filter table looks like this:

table inet filter {
        chain upnp {
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 17 accept
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 6 accept
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 17 accept
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 6 accept
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 17 accept
                iif "br1" @th,16,16 16422 @nh,128,32 3232235524 @nh,72,8 6 accept
        }
}

**Comment by svenauhagen** [comment]
Alright then let me test it and find out what the problem is. 
I am on the road currently but will be back on Monday to test and fix the problem.

**Comment by rtorrentuser** [comment]
> Alright then let me test it and find out what the problem is.

I did some further testing and  found a torrent client that uses UPNP but doesn't demand to remove the rules on its exit.  So both filter and nat rules remain in the table. On next program start same filter rules are added once again as described above. As for the nat rules, miniupnpd seems to check whether the the necessary rules are already in the table and doesn't duplicate them, which is clever to my mind...
I want to say that adding/deleting/checking nat rules seems to work ideally unlike filter rules...
Maybe this information could could be helpful...
Thanks for your efforts!

**Comment by svenauhagen** [comment]
@rtorrentuser 
I tested it on my end and both rules get deleted correctly when I test it with upnpc.

Which Kernel Version are you using?

**Comment by rtorrentuser** [comment]
> Which Kernel Version are you using?

4.19 (Debian Buster)

**Comment by svenauhagen** [comment]
That should work fine.
Can you start miniupnpd in debug mode (-d flag) and send me the output it generates?

**Comment by rtorrentuser** [comment]
> Can you start miniupnpd in debug mode (-d flag) and send me the output it generates?

See the attached file
[d-output.txt](https://github.com/miniupnp/miniupnp/files/3320847/d-output.txt)
.

**Comment by svenauhagen** [comment]
Thanks that helps a bit.
Unfortunately I do not have a test case here to reproduce it.

I added some debug output to the branch https://github.com/svenauhagen/miniupnp/tree/fixes/nftables
Can you rerun the -d output with that version and send me the output?

**Comment by rtorrentuser** [comment]
> Can you rerun the -d output with that version and send me the output?

Unable to compile:

netfilter_nft/nftnlrdr.c: In function ‘delete_redirect_and_filter_rules’:
netfilter_nft/nftnlrdr.c:265:31: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if (iaddr != 0 && iport != 0); {
                               ^
netfilter_nft/nftnlrdr.c:265:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (iaddr != 0 && iport != 0); {
  ^~
netfilter_nft/nftnlrdr.c:265:33: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (iaddr != 0 && iport != 0); {
                                 ^
netfilter_nft/nftnlrdr.c:46:26: warning: statement with no effect [-Wunused-value]
 #define d_printf(x) do { printf x; } while (0)
                          ^~~~~~
netfilter_nft/nftnlrdr.c:266:3: note: in expansion of macro ‘d_printf’
   d_printf("Trying to delete filter rule\n");
   ^~~~~~~~
netfilter_nft/nftnlrdr.c:266:12: error: expected ‘;’ before string constant
   d_printf("Trying to delete filter rule\n");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netfilter_nft/nftnlrdr.c:46:33: note: in definition of macro ‘d_printf’
 #define d_printf(x) do { printf x; } while (0)
                                 ^
make: *** [<builtin>: netfilter_nft/nftnlrdr.o] Error 1
<<< Compilation Error ... >>>

**Comment by rtorrentuser** [comment]
Ah.. Sorry...

Get this error:

netfilter_nft/nftnlrdr.c: In function ‘delete_redirect_and_filter_rules’:
netfilter_nft/nftnlrdr.c:46:26: warning: statement with no effect [-Wunused-value]
 #define d_printf(x) do { printf x; } while (0)
                          ^~~~~~
netfilter_nft/nftnlrdr.c:266:3: note: in expansion of macro ‘d_printf’
   d_printf("Trying to delete filter rule\n");
   ^~~~~~~~
netfilter_nft/nftnlrdr.c:266:12: error: expected ‘;’ before string constant
   d_printf("Trying to delete filter rule\n");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netfilter_nft/nftnlrdr.c:46:33: note: in definition of macro ‘d_printf’
 #define d_printf(x) do { printf x; } while (0)
                                 ^
make: *** [<builtin>: netfilter_nft/nftnlrdr.o] Error 1
<<< Compilation Error ... >>>

**Comment by svenauhagen** [comment]
Sorry, can you try it again. I fixed that error.

**Comment by rtorrentuser** [comment]
> Can you rerun the -d output with that version and send me the output?

[d-ouput-2.txt](https://github.com/miniupnp/miniupnp/files/3321375/d-ouput-2.txt)

**Comment by svenauhagen** [comment]
you sure that this was running under the new compiled version?
There is no debug output in the file you send.
There should be much more output in there.

**Comment by rtorrentuser** [comment]
> you sure that this was running under the new compiled version?

Sorry...
[d-output-3.txt](https://github.com/miniupnp/miniupnp/files/3321571/d-output-3.txt)

**Comment by rtorrentuser** [comment]
Debug output of one more program,  that uses UPNP (BiglyBT).  This time it hangs for some time at  "Trying to delete filter rule"
[d-output-4.txt](https://github.com/miniupnp/miniupnp/files/3321830/d-output-4.txt)

**Comment by miniupnp** [comment]
what's missing in _netfilter_nft/scripts_ is a script to display the current rules loaded in the MINUPNPD chains.

You then test with the following process : 
1. start miniupnpd
1. check that MINUPNPD chains are empty
1. call AddPortMapping (using upnpc -a)
1. check that both filter and nat rules are added to MINIUPNPD chains
1. call DeletePortMapping (using upnpc -d)
1. check that both filter and nat rules are removed.

@svenauhagen have you performed such tests ?

**Comment by svenauhagen** [comment]
I found the problem.
I always used custom chain names. Using the default chain names I can see the problem.
My match for the list is flawed since both the nat and filter chain have the same name in the default.
I always match filter rules to nat rules.
Let me write and test a fix.

**Comment by svenauhagen** [comment]
@rtorrentuser can you give it another try with this branch:

https://github.com/svenauhagen/miniupnp/tree/fixes/nftables

**Comment by rtorrentuser** [comment]
> @rtorrentuser can you give it another try with this branch:

Everything works fine now! Thank you very much, @svenauhagen.

**Comment by svenauhagen** [comment]
Great!
Let me clean this up and do a fresh PR for @miniupnp
